version: '3.1'

services:
  database:
    container_name: api-walea
    image: postgis/postgis:11-3.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_USER: walea
      POSTGRES_DB: walea